[package]
name = 'staking'
version = '1.0.0'

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "093b497d1267715a222845aad4fd3ca59da90e8d" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "093b497d1267715a222845aad4fd3ca59da90e8d" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "093b497d1267715a222845aad4fd3ca59da90e8d" }

[addresses]
contract_addr='3d8d1ec470e29a3e60c10fe19d9628024535c6e570696d84e475b9298bcd99e3'